version: '2'
services:
  rabbitmq:
    container_name: rabbitmq-container
    image: docker.io/bitnami/rabbitmq:3.12
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_LOGS=-
    volumes:
      - 'rabbitmqdata:/bitnami/rabbitmq/mnesia'
    # networks:
    #   - net-rabbit
volumes:
  rabbitmqdata:
    driver: local