version: '3'
volumes:
  timescaledata:
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: timescaledb
      POSTGRES_PASSWORD: password
    volumes:
      - timescaledata:/var/lib/postgresql/data
  # prometheus_postgresql_adapter:
  #   depends_on:
  #   - timescaledb
  #   environment:
  #     TS_PROM_LOG_LEVEL: debug
  #     TS_PROM_DB_CONNECT_RETRIES: 10
  #     TS_PROM_DB_HOST: timescaledb
  #     TS_PROM_DB_USER: timescaledb
  #     TS_PROM_DB_PASSWORD: password
  #     TS_PROM_DB_NAME: postgres
  #     TS_PROM_WEB_TELEMETRY_PATH: /metrics-text
  #   image: timescale/timescale-prometheus:latest
  #   restart: always
  #   ports:
  #   - 9201:9201/tcp