version: '3'
networks:
  net-cache:
    driver: bridge
volumes:
  # fastdata:
  # flaskdata:
  # pgdata:
  #   driver: local
  # mysqldata:
  redisdata:
    driver: local
  # prometheusdata:
  # grafanadata:
services:
  # mongo:
  #   image: mongo:latest
  # crdb:
  #   image: cockroachdb/cockroach:v19.2.2
  #   ports:
  #     - "26257:26257"
  #     - "8080:8080"
  #   command: start-single-node --insecure
  #   volumes:
  #     - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"
  # cadvisor:
  #   image: google/cadvisor
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   ports:
  #     - 8080:8080
  #   restart: always
  #   deploy:
  #     mode: global

  vault:
    image: docker.io/bitnami/vault:1

  redis:
    image: docker.io/bitnami/redis:latest
    container_name: redis-container
    ports:
      - 6379:6379
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      # - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - redisdata:/bitnami/redis/data
    networks:
      - net-cache
