{
 "title": "Redis - Overall Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "type",
    "label": "Node Type",
    "query": {
     "query": "label_values(kube_pod_labels{pod=~\".*redis.*\",label_role!=\"metrics\"}, label_role)"
    }
   },
   {
    "name": "owner",
    "label": "Owner",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container=~\".*redis.*\",name=~\".*slave.*\"},container)"
    }
   },
   {
    "name": "pod",
    "label": "POD",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container=~\"^redis-?($owner).*\",name=~\".*$type.*\"},pod)"
    }
   },
   {
    "name": "cmd",
    "label": "Command",
    "query": {
     "query": "label_values(redis_commands_duration_seconds_total{addr=~\".*$type.*\",addr=~\".*($owner).*\"},cmd)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "POD Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{container!=\"POD\",container=~\"redis-?($owner).*\",name=~\".*$type.*\",pod=~\"$pod\"}[30m])>0.05",
     "legendFormat": "{{namespace}} {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{container!=\"POD\",container=~\"redis-?($owner).*\",name=~\".*$type.*\",pod=~\"$pod\"}>200000000",
     "legendFormat": "{{namespace}} {{pod}}"
    }
   ]
  },
  {
   "title": "Redis Metrics - $owner",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Commands Count Overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_commands_total{addr=~\".*$type.*\",addr=~\".*($owner).*\",cmd=~\"$cmd\"}[$__interval])>1) by (namespace,addr,cmd)",
     "legendFormat": "{{namespace}} {{ addr }} - {{ cmd }}"
    }
   ]
  },
  {
   "title": "Commands Duration Overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_duration_seconds_total{addr=~\".*$type.*\",addr=~\".*($owner).*\",cmd=~\"$cmd\"}[$__interval])) by (namesapce,addr,cmd)>0.0001",
     "legendFormat": "{{namespace}} {{ addr }} - {{ cmd }}"
    }
   ]
  },
  {
   "title": "Key Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_db_keys{addr=~\".*$type.*\",addr=~\".*($owner).*\"}) by (addr) - sum(redis_db_keys_expiring{addr=~\".*($owner).*\"}) by (addr)>1000",
     "legendFormat": "{{ addr }} {{ db }}- Non-Expiring"
    },
    {
     "expr": "sum(redis_db_keys_expiring{addr=~\".*$type.*\",addr=~\".*($owner).*\"}) by (addr,db)>100",
     "legendFormat": "{{ addr }} {{ db }}- Expiring"
    }
   ]
  },
  {
   "title": "Cache Hit/Miss",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{addr=~\".*$type.*\",addr=~\".*($owner).*\"}[$__interval]) / (1 + irate(redis_keyspace_hits_total{addr=~\".*$type.*\",addr=~\".*($owner).*\"}[$__interval]) + irate(redis_keyspace_misses_total{addr=~\".*$type.*\",addr=~\".*($owner).*\"}[$__interval]))",
     "legendFormat": "{{ addr }}"
    }
   ]
  }
 ]
}